name: Validate HACS

on:
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@11d5960a326750d5838078e36cf38b85af677262' # v4
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:prod
      - name: HACS validation
        uses: 'hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa'
        with:
          category: 'plugin'
